/// COFFEE — Standard Sui Coin representing tokenized Jamaica Blue Mountain Coffee.
///
/// Generated by generate-commodity.sh
/// Deploy: sui client upgrade --upgrade-capability UPGRADE_CAP --gas-budget 100000000
module anansi::coffee {
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::url;
    use sui::clock::Clock;
    use std::string::String;
    use anansi::asset_pool::{Self, CustodianCap, Lot};
    use anansi::compliance::{Self, ComplianceRegistry};

    // ============ One-Time Witness ============

    public struct COFFEE has drop {}

    // ============ Objects ============

    public struct MintVault has key {
        id: UID,
        cap: TreasuryCap<COFFEE>,
    }

    // ============ Init ============

    fun init(witness: COFFEE, ctx: &mut TxContext) {
        let (cap, metadata) = coin::create_currency(
            witness,
            6,
            b"COFFEE",
            b"Jamaica Blue Mountain Coffee",
            b"Tokenized Jamaica Blue Mountain coffee.",
            option::some(url::new_unsafe_from_bytes(
                b"https://spice.anansi.tech/tokens/coffee.png"
            )),
            ctx,
        );

        transfer::public_freeze_object(metadata);

        transfer::share_object(MintVault {
            id: object::new(ctx),
            cap,
        });
    }

    // ============ Delivery + Minting ============

    public fun record_delivery(
        vault: &mut MintVault,
        cap: &CustodianCap,
        lot: &mut Lot,
        registry: &ComplianceRegistry,
        farmer: address,
        units: u64,
        grade: vector<u8>,
        receipt_hash: vector<u8>,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        compliance::assert_can_participate(registry, farmer);

        let coin_amount = units * 1_000_000;

        asset_pool::record_delivery(
            cap, lot, farmer, units, coin_amount, grade, receipt_hash, clock, ctx
        );

        let coin = coin::mint(&mut vault.cap, coin_amount, ctx);
        transfer::public_transfer(coin, farmer);
    }

    // ============ View Functions ============

    public fun total_supply(vault: &MintVault): u64 {
        coin::total_supply(&vault.cap)
    }
}
