/// COCOA — Standard Sui Coin representing tokenized Grenada Cocoa.
///
/// Separate package. Imports core for lot tracking and compliance.
/// Generated by generate-commodity.sh
module anansi_cocoa::cocoa {
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::url;
    use sui::clock::Clock;
    use anansi::asset_pool::{Self, CustodianCap, Lot};
    use anansi::compliance::{Self, ComplianceRegistry};

    // ============ One-Time Witness ============

    public struct COCOA has drop {}

    // ============ Objects ============

    public struct MintVault has key {
        id: UID,
        cap: TreasuryCap<COCOA>,
    }

    // ============ Init ============

    fun init(witness: COCOA, ctx: &mut TxContext) {
        let (cap, metadata) = coin::create_currency(
            witness,
            6,
            b"COCOA",
            b"Grenada Cocoa",
            b"Tokenized Grenada Cocoa on the Spice platform.",
            option::some(url::new_unsafe_from_bytes(
                b"https://spice.anansi.tech/tokens/cocoa.png"
            )),
            ctx,
        );

        transfer::public_freeze_object(metadata);
        transfer::share_object(MintVault { id: object::new(ctx), cap });
    }

    // ============ Delivery + Minting ============

    public fun record_delivery(
        vault: &mut MintVault,
        cap: &CustodianCap,
        lot: &mut Lot,
        registry: &ComplianceRegistry,
        farmer: address,
        units: u64,
        grade: vector<u8>,
        receipt_hash: vector<u8>,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        compliance::assert_can_participate(registry, farmer);

        let coin_amount = units * 1_000_000;

        asset_pool::record_delivery(
            cap, lot, farmer, units, coin_amount, grade, receipt_hash, clock, ctx
        );

        let coin = coin::mint(&mut vault.cap, coin_amount, ctx);
        transfer::public_transfer(coin, farmer);
    }

    // ============ View Functions ============

    public fun total_supply(vault: &MintVault): u64 {
        coin::total_supply(&vault.cap)
    }
}
