#!/bin/bash
# ============================================================
# generate-commodity.sh — Generate a new commodity Move module
#
# Usage:
#   ./generate-commodity.sh COCOA "Grenada Cocoa"
#   ./generate-commodity.sh COFFEE "Jamaica Blue Mountain Coffee" "Tokenized Jamaica Blue Mountain coffee." coffee.png
#   ./generate-commodity.sh VILLA "Antigua Villa Share" "Fractional ownership of Antiguan luxury villas." villa.png
#   ./generate-commodity.sh RUM "Barbados Rum Revenue" "Tokenized revenue from Barbados rum distillery." rum.png
#   ./generate-commodity.sh IDNUT "Indonesian Nutmeg" "Tokenized Indonesian nutmeg." idnut.png
#
# After running, follow the printed instructions.
# ============================================================

set -e

SYMBOL="$1"
NAME="$2"
DESCRIPTION="${3:-Tokenized ${NAME} on the Spice platform.}"
MODULE_NAME="$(printf '%s' "$SYMBOL" | tr '[:upper:]' '[:lower:]')"
ICON="${4:-${MODULE_NAME}.png}"

if [ -z "$SYMBOL" ] || [ -z "$NAME" ]; then
  echo ""
  echo "  generate-commodity.sh — Generate a new Spice commodity Move module"
  echo ""
  echo "  Usage: $0 SYMBOL \"Full Name\" [\"Description\"] [icon.png]"
  echo ""
  echo "  Examples:"
  echo "    $0 COCOA \"Grenada Cocoa\""
  echo "    $0 COFFEE \"Jamaica Blue Mountain Coffee\""
  echo "    $0 VILLA \"Antigua Villa Share\" \"Fractional ownership of Antiguan luxury villas.\""
  echo "    $0 RUM \"Barbados Rum Revenue\" \"Tokenized revenue from Barbados rum distillery.\""
  echo "    $0 IDNUT \"Indonesian Nutmeg\""
  echo "    $0 MACE \"Grenada Mace\""
  echo ""
  exit 1
fi

OUTPUT_FILE="${MODULE_NAME}.move"

cat > "$OUTPUT_FILE" << MOVEEOF
/// ${SYMBOL} — Standard Sui Coin representing tokenized ${NAME}.
///
/// Generated by generate-commodity.sh
/// Deploy: sui client upgrade --upgrade-capability UPGRADE_CAP --gas-budget 100000000
module anansi::${MODULE_NAME} {
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::url;
    use sui::clock::Clock;
    use std::string::String;
    use anansi::asset_pool::{Self, CustodianCap, Lot};
    use anansi::compliance::{Self, ComplianceRegistry};

    // ============ One-Time Witness ============

    public struct ${SYMBOL} has drop {}

    // ============ Objects ============

    public struct MintVault has key {
        id: UID,
        cap: TreasuryCap<${SYMBOL}>,
    }

    // ============ Init ============

    fun init(witness: ${SYMBOL}, ctx: &mut TxContext) {
        let (cap, metadata) = coin::create_currency(
            witness,
            6,
            b"${SYMBOL}",
            b"${NAME}",
            b"${DESCRIPTION}",
            option::some(url::new_unsafe_from_bytes(
                b"https://spice.anansi.tech/tokens/${ICON}"
            )),
            ctx,
        );

        transfer::public_freeze_object(metadata);

        transfer::share_object(MintVault {
            id: object::new(ctx),
            cap,
        });
    }

    // ============ Delivery + Minting ============

    public fun record_delivery(
        vault: &mut MintVault,
        cap: &CustodianCap,
        lot: &mut Lot,
        registry: &ComplianceRegistry,
        farmer: address,
        units: u64,
        grade: vector<u8>,
        receipt_hash: vector<u8>,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        compliance::assert_can_participate(registry, farmer);

        let coin_amount = units * 1_000_000;

        asset_pool::record_delivery(
            cap, lot, farmer, units, coin_amount, grade, receipt_hash, clock, ctx
        );

        let coin = coin::mint(&mut vault.cap, coin_amount, ctx);
        transfer::public_transfer(coin, farmer);
    }

    // ============ View Functions ============

    public fun total_supply(vault: &MintVault): u64 {
        coin::total_supply(&vault.cap)
    }
}
MOVEEOF

echo ""
echo "  ✓ Generated ${OUTPUT_FILE}"
echo ""
echo "  ┌─────────────────────────────────────────────────────────────┐"
echo "  │  Next steps                                                 │"
echo "  └─────────────────────────────────────────────────────────────┘"
echo ""
echo "  1. Copy to contracts:"
echo "     cp ${OUTPUT_FILE} ../contracts/sources/"
echo ""
echo "  2. Build and upgrade (NOT publish):"
echo "     cd ../contracts"
echo "     rm Move.lock"
echo "     sui move build"
echo "     sui client upgrade --upgrade-capability 0xYOUR_UPGRADE_CAP --gas-budget 100000000"
echo ""
echo "  3. Find the MintVault ID in the upgrade output:"
echo "     Look for: ${MODULE_NAME}::MintVault (Shared) → 0x..."
echo ""
echo "  4. Update environment variables:"
echo ""
echo "     Add ${SYMBOL} to NEXT_PUBLIC_REGISTERED_TOKENS:"
echo "       NEXT_PUBLIC_REGISTERED_TOKENS=...,${SYMBOL}"
echo ""
echo "     Add to NEXT_PUBLIC_TOKEN_CONFIG JSON:"
echo "       \"${SYMBOL}\":{\"mintVault\":\"0xMINT_VAULT_ID\",\"pool\":\"\"}"
echo ""
echo "     ⚠️  Token config MUST be a single JSON env var."
echo "     Next.js does not support dynamic process.env access client-side."
echo "     See README.md for details."
echo ""
echo "  5. Create asset type from /platform dashboard:"
echo "     Symbol: ${SYMBOL}"
echo "     Name: ${NAME}"
echo ""
echo "  6. (Optional) Create Cetus DEX pool from /admin/cetus"
echo "     After creating the pool, add the pool ID to NEXT_PUBLIC_TOKEN_CONFIG:"
echo "       \"${SYMBOL}\":{\"mintVault\":\"0x...\",\"pool\":\"0xPOOL_ID\"}"
echo ""
echo "  7. Redeploy to Vercel. The app discovers ${SYMBOL} automatically."
echo ""
