#!/bin/bash
# ============================================================
# generate-commodity.sh — Generate a new commodity Move module
#
# Usage:
#   ./scripts/generate-commodity.sh COCOA "Grenada Cocoa" "Tokenized Grenada cocoa backed by GCA warehouse receipts." cocoa.png
#   ./scripts/generate-commodity.sh COFFEE "Jamaica Blue Mountain Coffee" "Tokenized Jamaica Blue Mountain coffee." coffee.png
#   ./scripts/generate-commodity.sh VILLA "Antigua Villa Share" "Fractional ownership of Antiguan luxury villas." villa.png
#   ./scripts/generate-commodity.sh RUM "Barbados Rum Revenue" "Tokenized revenue from Barbados rum distillery." rum.png
#   ./scripts/generate-commodity.sh IDNUT "Indonesian Nutmeg" "Tokenized Indonesian nutmeg." idnut.png
#
# After running:
#   1. Copy the generated file to contracts/sources/
#   2. sui client upgrade --upgrade-capability 0xYOUR_UPGRADE_CAP --gas-budget 100000000
#   3. Add env vars:
#      NEXT_PUBLIC_REGISTERED_TOKENS=NUTMEG,COCOA  (add to list)
#      NEXT_PUBLIC_TOKEN_COCOA_MINT_VAULT=0x...     (from deploy output)
#      NEXT_PUBLIC_TOKEN_COCOA_POOL=0x...           (after creating Cetus pool)
#   4. Create asset type from /platform dashboard
#   5. Create Cetus pool from /admin/cetus
# ============================================================

set -e

SYMBOL="$1"
NAME="$2"
DESCRIPTION="${3:-Tokenized ${NAME} on the Spice platform.}"
ICON="${4:-${SYMBOL,,}.png}"

if [ -z "$SYMBOL" ] || [ -z "$NAME" ]; then
  echo "Usage: $0 SYMBOL \"Full Name\" [\"Description\"] [icon.png]"
  echo ""
  echo "Examples:"
  echo "  $0 COCOA \"Grenada Cocoa\""
  echo "  $0 COFFEE \"Jamaica Blue Mountain Coffee\" \"Tokenized Jamaica Blue Mountain coffee.\" coffee.png"
  echo "  $0 VILLA \"Antigua Villa Share\" \"Fractional ownership of Antiguan luxury villas.\""
  echo "  $0 RUM \"Barbados Rum Revenue\""
  echo "  $0 IDNUT \"Indonesian Nutmeg\""
  exit 1
fi

MODULE_NAME="${SYMBOL,,}"  # lowercase
OUTPUT_FILE="${MODULE_NAME}.move"

cat > "$OUTPUT_FILE" << MOVEEOF
/// ${SYMBOL} — Standard Sui Coin representing tokenized ${NAME}.
///
/// Generated by generate-commodity.sh
/// Deploy: sui move build && sui client publish --gas-budget 100000000
module anansi::${MODULE_NAME} {
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::url;
    use sui::clock::Clock;
    use std::string::String;
    use anansi::asset_pool::{Self, CustodianCap, Lot};
    use anansi::compliance::{Self, ComplianceRegistry};

    // ============ One-Time Witness ============

    public struct ${SYMBOL} has drop {}

    // ============ Objects ============

    public struct MintVault has key {
        id: UID,
        cap: TreasuryCap<${SYMBOL}>,
    }

    // ============ Init ============

    fun init(witness: ${SYMBOL}, ctx: &mut TxContext) {
        let (cap, metadata) = coin::create_currency(
            witness,
            6,
            b"${SYMBOL}",
            b"${NAME}",
            b"${DESCRIPTION}",
            option::some(url::new_unsafe_from_bytes(
                b"https://spice.anansi.tech/tokens/${ICON}"
            )),
            ctx,
        );

        transfer::public_freeze_object(metadata);

        transfer::share_object(MintVault {
            id: object::new(ctx),
            cap,
        });
    }

    // ============ Delivery + Minting ============

    public fun record_delivery(
        vault: &mut MintVault,
        cap: &CustodianCap,
        lot: &mut Lot,
        registry: &ComplianceRegistry,
        farmer: address,
        units: u64,
        grade: vector<u8>,
        receipt_hash: vector<u8>,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        compliance::assert_can_participate(registry, farmer);

        let coin_amount = units * 1_000_000;

        asset_pool::record_delivery(
            cap, lot, farmer, units, coin_amount, grade, receipt_hash, clock, ctx
        );

        let coin = coin::mint(&mut vault.cap, coin_amount, ctx);
        transfer::public_transfer(coin, farmer);
    }

    // ============ View Functions ============

    public fun total_supply(vault: &MintVault): u64 {
        coin::total_supply(&vault.cap)
    }
}
MOVEEOF

echo "✓ Generated ${OUTPUT_FILE}"
echo ""
echo "Next steps:"
echo "  1. cp ${OUTPUT_FILE} contracts/sources/"
echo "  2. cd contracts && rm move.lock && sui move build"
echo "  3. sui client upgrade --upgrade-capability 0xYOUR_UPGRADE_CAP --gas-budget 100000000
echo "  4. Add to .env.local:"
echo "     NEXT_PUBLIC_REGISTERED_TOKENS=...,${SYMBOL}"
echo "     NEXT_PUBLIC_TOKEN_${SYMBOL}_MINT_VAULT=<MintVault ID from deploy>"
echo "     NEXT_PUBLIC_TOKEN_${SYMBOL}_POOL=<Pool ID after creating Cetus pool>"
echo "  5. Create asset type from /platform: symbol=${SYMBOL}, name=${NAME}"
echo "  6. Create Cetus pool from /admin/cetus"
