#!/bin/bash
# ============================================================
# generate-commodity.sh — Generate a new commodity package
#
# Creates a complete Sui Move package directory with Move.toml
# and source file, ready to build and publish.
#
# Usage:
#   ./generate-commodity.sh COCOA "Grenada Cocoa"
#   ./generate-commodity.sh COFFEE "Jamaica Blue Mountain Coffee"
#   ./generate-commodity.sh VILLA "Antigua Villa Share" "Fractional ownership of Antiguan luxury villas."
#   ./generate-commodity.sh RUM "Barbados Rum Revenue" "Tokenized revenue from Barbados rum distillery."
#   ./generate-commodity.sh IDNUT "Indonesian Nutmeg"
# ============================================================

set -e

SYMBOL="$1"
NAME="$2"

if [ -z "$SYMBOL" ] || [ -z "$NAME" ]; then
  echo ""
  echo "  generate-commodity.sh — Generate a new Spice commodity package"
  echo ""
  echo "  Usage: $0 SYMBOL \"Full Name\" [\"Description\"] [icon.png]"
  echo ""
  echo "  Examples:"
  echo "    $0 COCOA \"Grenada Cocoa\""
  echo "    $0 COFFEE \"Jamaica Blue Mountain Coffee\""
  echo "    $0 VILLA \"Antigua Villa Share\" \"Fractional ownership...\""
  echo "    $0 RUM \"Barbados Rum Revenue\" \"Tokenized revenue...\""
  echo "    $0 IDNUT \"Indonesian Nutmeg\""
  echo ""
  exit 1
fi

# ============================================================
# CROSS-PLATFORM STRING FORMATTING
# ============================================================
# Safely convert to uppercase/lowercase using 'tr' instead of Bash 4.0 syntax
SYMBOL_UPPER=$(echo "$SYMBOL" | tr '[:lower:]' '[:upper:]')
SYMBOL_LOWER=$(echo "$SYMBOL" | tr '[:upper:]' '[:lower:]')

DESCRIPTION="${3:-Tokenized ${NAME} on the Spice platform.}"
ICON="${4:-${SYMBOL_LOWER}.png}"

MODULE_NAME="${SYMBOL_LOWER}"
PKG_NAME="anansi_${MODULE_NAME}"

# 1. Resolve absolute paths so the script can be run from anywhere
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PKG_DIR="$SCRIPT_DIR/../../contracts/commodities/${MODULE_NAME}"

if [ -d "$PKG_DIR" ]; then
  echo "  ✗ Package directory already exists: ${PKG_DIR}"
  exit 1
fi

# Create package directory
mkdir -p "${PKG_DIR}/sources"

# Generate Move.toml
cat > "${PKG_DIR}/Move.toml" << TOMLEOF
[package]
name = "${PKG_NAME}"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
anansi = { local = "../../core" }

[addresses]
${PKG_NAME} = "0x0"
TOMLEOF

# Generate source file
cat > "${PKG_DIR}/sources/${MODULE_NAME}.move" << MOVEEOF
/// ${SYMBOL_UPPER} — Standard Sui Coin representing tokenized ${NAME}.
///
/// Separate package. Imports core for lot tracking and compliance.
/// Generated by generate-commodity.sh
module ${PKG_NAME}::${MODULE_NAME} {
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::url;
    use sui::clock::Clock;
    use anansi::asset_pool::{Self, CustodianCap, Lot};
    use anansi::compliance::{Self, ComplianceRegistry};

    // ============ One-Time Witness ============

    public struct ${SYMBOL_UPPER} has drop {}

    // ============ Objects ============

    public struct MintVault has key {
        id: UID,
        cap: TreasuryCap<${SYMBOL_UPPER}>,
    }

    // ============ Init ============

    fun init(witness: ${SYMBOL_UPPER}, ctx: &mut TxContext) {
        let (cap, metadata) = coin::create_currency(
            witness,
            6,
            b"${SYMBOL_UPPER}",
            b"${NAME}",
            b"${DESCRIPTION}",
            option::some(url::new_unsafe_from_bytes(
                b"https://spice.anansi.tech/tokens/${ICON}"
            )),
            ctx,
        );

        transfer::public_freeze_object(metadata);
        transfer::share_object(MintVault { id: object::new(ctx), cap });
    }

    // ============ Delivery + Minting ============

    public fun record_delivery(
        vault: &mut MintVault,
        cap: &CustodianCap,
        lot: &mut Lot,
        registry: &ComplianceRegistry,
        farmer: address,
        units: u64,
        grade: vector<u8>,
        receipt_hash: vector<u8>,
        clock: &Clock,
        ctx: &mut TxContext,
    ) {
        compliance::assert_can_participate(registry, farmer);

        let coin_amount = units * 1_000_000;

        asset_pool::record_delivery(
            cap, lot, farmer, units, coin_amount, grade, receipt_hash, clock, ctx
        );

        let coin = coin::mint(&mut vault.cap, coin_amount, ctx);
        transfer::public_transfer(coin, farmer);
    }

    // ============ View Functions ============

    public fun total_supply(vault: &MintVault): u64 {
        coin::total_supply(&vault.cap)
    }
}
MOVEEOF

echo "============================================================"
echo "  🎉 COMMODITY GENERATED: ${SYMBOL_UPPER}"
echo "============================================================"
echo "  Generated package: ${PKG_DIR}/"
echo "    ├── Move.toml"
echo "    └── sources/${MODULE_NAME}.move"
echo "============================================================"
echo "  Next: Deploy with ./deploy-commodity.sh ${MODULE_NAME}"
echo ""